language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  - 7.0
  # - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - develop


cache:
  directories:
    # - vendor
    - $HOME/.composer/cache
git:
  depth: 1

addons:
  mariadb: '10.1'
  firefox: "47.0.1"
  hosts:
  - localhost
  - xepan-local.org
  - demo.xepan-local.org

install:
  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
  - wget -P ~/Downloads https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz
  - tar -xf ~/Downloads/geckodriver-v0.10.0-linux64.tar.gz -C ~/Downloads
  - composer self-update
  - composer install --prefer-source
  - ulimit -c unlimited || true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f tests/travis/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - java -jar selenium-server-standalone-2.53.1.jar -port 4444 > /dev/null &
  - sleep 5
  - mkdir websites && cd websites && mkdir www && cd www && mkdir assets && mkdir upload && echo "<?php $config['dsn']='mysql://root:@localhost/xepan2';$config['test_mode']=true;" >> config.php && git clone https://github.com/xepan/epanwebsite.git www
  - cd ..
  - mkdir demo && cd demo && upload && echo "<?php $config['dsn']='mysql://root:@localhost/demo';$config['test_mode']=true;" >> config.php && cp vendor/xepan/cms/templates/defaultlayout/www www
  - cd ../..
  - mysql -e 'create database xepan2;'
  - mysql -e 'create database demo;'
  - mysql -uroot xepan2 < tests/_data/websitedata.sql
  - mysql -uroot xepan2 < tests/_data/data.sql
  - php vendor/codeception/codeception/codecept build
  
script:
  - php vendor/codeception/codeception/codecept run website --env travis
  - php vendor/codeception/codeception/codecept run erp --env travis