language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  - 7.0
  # - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - develop

addons:
  mariadb: '10.0'

cache:
  directories:
    # - vendor
    - $HOME/.composer/cache
git:
  depth: 1

install:
  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
  - composer self-update
  - composer install --prefer-source
  - ulimit -c unlimited || true

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  # - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - java -jar selenium-server-standalone-2.53.1.jar -port 4444 > /dev/null &
  - sleep 5
  - mkdir websites && cd websites && mkdir assets && mkdir upload && echo "<?php $config['dsn']='mysql://root:@localhost/xepan2';$config['test_mode']=true;" >> config.php && git clone https://github.com/xepan/epanwebsite.git www
  - cd ..
  - mysql -e 'create database xepan2;'
  - mysql -e 'create database demo;'
  - mysql -uroot xepan2 < tests/_data/websitedata.sql
  - mysql -uroot xepan2 < tests/_data/data.sql
  - php -S localhost:8080 > /dev/null &
  - php vendor/codeception/codeception/codecept build website
  - php vendor/codeception/codeception/codecept build erp
  
script:
  - php vendor/codeception/codeception/codecept run  # self tests
  - php vendor/codeception/codeception/codecept run website